### ISSUE TITLE
Use Cases/ Class Diagrams

### ISSUE THREAD

**Issue by randomittin** [HackerDM/Home-Automation#5]
@rishab178 
@Tanuja-Sawant 

Finish this by WednesDay!

**Comment by rishab178** [comment]
Aye Aye captain!

**Comment by shreypareek** [comment]
Should the methods of the classes Twitter, Facebook, Dropbox and Gmail classes be static as well? So that the methods can be called on without instantiating an object of the class. I think that is what you had in mind when you have said that the variables should be static. If you feel that the methods should be static too, confirm here, i'll make the necessary changes.

**Comment by shreypareek** [comment]
Also, could you specify, what some of the methods are intended to do. Like getNotify() for the settings classes. I could not infer their meaning from the class diagram itself.

**Comment by rishab178** [comment]
Notify is a setting for the user to change as in does he want to get the notification via say facebook or not and getNotify and setNotify are just the variable's getters and setters.
If notify is  true, the user gets the notification or else he doesn't.

About the static methods in the Facebook, Twitter, etc class:
Umm, I am not really sure about that. If it creates no problem in implementation then they could be made static. It would maybe make the code more efficient. Although what I meant from the note was that the methods of the class FacebookSettings, TwitterSettings, etc should be static so that we do not have to set them differently for every object that we create of that class because for a specific user these settings will be "<i>static</i>" :tongue:
